# Generated by Django 3.1.7 on 2021-03-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(verbose_name='customer_id')),
                ('review_id', models.IntegerField(verbose_name='review_id')),
                ('product_id', models.IntegerField(verbose_name='product_id')),
                ('review_data', models.DateTimeField(verbose_name='Review Date')),
                ('review_star', models.IntegerField(verbose_name='review_star')),
                ('review_title', models.TextField(verbose_name='review_title')),
            ],
        ),
    ]
