# Generated by Django 3.1.7 on 2021-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='product_id')),
                ('product_title', models.TextField(verbose_name='product_title')),
                ('product_category', models.TextField(verbose_name='product_category')),
                ('total_votes', models.IntegerField(verbose_name='total_votes')),
            ],
        ),
    ]
