# Generated by Django 3.1.7 on 2021-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.TextField(verbose_name='review_id'),
        ),
    ]
