# Generated by Django 3.1.7 on 2021-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20210326_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.TextField(verbose_name='customer_id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.TextField(verbose_name='product_id'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer_id',
            field=models.TextField(verbose_name='customer_id'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.TextField(verbose_name='product_id'),
        ),
    ]
